version: "3.8"

services:
  web1:
    image: nginx:alpine
    ports:
      - "8080:80"
    networks:
      - mynet

  web2:
    image: nginx:alpine
    networks:
      - mynet

networks:
  mynet:
    driver: overlay

