version: "3.8"

services:
  jenkins:
    image: my_mvn_jenkins:1
    ports:
      - "50000:50000"  # optional: JNLP port
    volumes:
      - /Users/LudwigU/docker_volumes/jenkins_home_data:/var/jenkins_home
    networks:
      - jenkins_net

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - jenkins
    networks:
      - jenkins_net

networks:
  jenkins_net:
    driver: bridge

