---
networks:
  monitor-net:

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.20
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - monitor-net


  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.20
    container_name: logstash
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash/filebeat-template.json:/usr/share/logstash/templates/filebeat-template.json
    ports:
      - "5000:5000"     # Log Input
      - "9600:9600"     # Monitoring API
      - "514:514/udp"     # Monitoring API
      - "514:514/tcp"     # Monitoring API
    networks:
      - monitor-net


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus_windos.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "472"
    volumes:
      - /home/ludwigu/docker_volumes/grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - monitor-net

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    pid: "host"
    networks:
      - monitor-net

volumes:
  esdata: