version: '3.8'

networks:
  monitor-net:

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus_linux.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - /home/uwe/docker_volumes/grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - monitor-net

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    pid: "host"
    networks:
      - monitor-net
