scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']  # Use Docker service name

  - job_name: 'remote_node'
    static_configs:
      - targets: ['host.docker.internal:19100']  # macOS host bridge